/*
 * Lent.java
 *
 * Created on __DATE__, __TIME__
 */

package page;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import model.BookModel;
import dao.LentDao;
import dao.StudentDao;

/**
 *
 * @author  __USER__
 */
public class Lent extends javax.swing.JFrame {
	/**
	 * 序列号
	 */
	private static final long serialVersionUID = 1L;

	BookModel bookModel;

	/** Creates new form Lent */
	public Lent() {
		initComponents();
		this.setBounds(150, 50, 1050, 650);
		//设置背景
		setBackgroudImage();
		//窗体大小不可变
		this.setResizable(false);
		//设置窗体图标
		Toolkit tool = this.getToolkit(); //得到一个Toolkit对象
		Image myimage = tool.getImage("img/4.png"); //由tool获取图像
		this.setIconImage(myimage);
	}

	/** Creates new form Lent构造方法 */
	public Lent(BookModel bookModel) {
		this.bookModel = bookModel;
		initComponents();
		this.setBounds(150, 50, 1050, 650);
		//设置背景
		setBackgroudImage();
		//窗体大小不可变
		this.setResizable(false);

		this.bno.setText(bookModel.getBno());
		this.bname.setText(bookModel.getName());
	}

	/** 
	 * 初始化借书窗体背景 
	 */
	private void setBackgroudImage() {
		((JPanel) this.getContentPane()).setOpaque(false);
		ImageIcon img = new ImageIcon("img/lent.jpg"); // 添加图片  
		JLabel lb_backgroud = new JLabel(img);
		this.getLayeredPane().add(lb_backgroud, new Integer(Integer.MIN_VALUE));
		lb_backgroud.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		bno = new javax.swing.JTextField();
		bname = new javax.swing.JTextField();
		sno = new javax.swing.JTextField();
		submit = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u56fe\u4e66\u7ba1\u7406\u7cfb\u7edf>\u501f\u8fd8\u670d\u52a1>\u501f\u4e66\u670d\u52a1");

		bno.setEditable(false);
		bno.setFont(new java.awt.Font("微软雅黑", 0, 18));
		bno.setBorder(null);

		bname.setEditable(false);
		bname.setFont(new java.awt.Font("微软雅黑", 0, 18));
		bname.setBorder(null);

		sno.setFont(new java.awt.Font("微软雅黑", 0, 18));
		sno.setBorder(null);

		submit.setFont(new java.awt.Font("楷体", 0, 30));
		submit.setForeground(new java.awt.Color(255, 255, 255));
		submit.setText("\u63d0\u4ea4");
		submit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				submitMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				243,
																				243,
																				243)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								sno,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								244,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								bname,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								244,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								bno,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								244,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				442,
																				442,
																				442)
																		.addComponent(
																				submit)))
										.addContainerGap(459, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(194, 194, 194)
						.addComponent(bno,
								javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								61, 61, 61).addComponent(bname,
								javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								57, 57, 57).addComponent(sno,
								javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								60, 60, 60).addComponent(submit)
						.addContainerGap(62, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 点击借出图书
	 */
	private void submitMouseClicked(java.awt.event.MouseEvent evt) {
		String bno = this.bno.getText();
		String bname = this.bname.getText();
		String sno = this.sno.getText();
		BookModel book = new BookModel();
		book.setBno(bno);
		book.setName(bname);
		//判断图书编号是否重复
		//图书新增
		StudentDao sd=new StudentDao();
		boolean b = sd.haveStu(sno);
		if(b){
			LentDao ld = new LentDao();
			ld.lentBook(book, sno);
			JOptionPane.showMessageDialog(null, "借书成功");
			
		}else{
			JOptionPane.showMessageDialog(null, "此同学没有借书权限");
			//System.out.println("您没有借书权限,如要借书请找图书管理员");
		}
		//跳转到queryService页面
		new LentBack().setVisible(true);
		//跳转完关闭原来页面
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Lent().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField bname;
	private javax.swing.JTextField bno;
	private javax.swing.JTextField sno;
	private javax.swing.JLabel submit;
	// End of variables declaration//GEN-END:variables

}