/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package page;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import jdbc.ValidCode;
import dao.LoginDao;

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JFrame {
	/**
	 * 序列号
	 */
	private static final long serialVersionUID = 1L;

	LoginDao loginDao = new LoginDao();

	/**
	 * 验证码实例化
	 */
	ValidCode validCode = new ValidCode();

	/** Creates new form Login */
	public Login() {
		initComponents();
		//设置窗体大小
		this.setBounds(150, 50, 1050, 650);
		//设置背景
		setBackgroudImage();
		//窗体大小不可变
		this.setResizable(false);
		//设置窗体图标
		Toolkit tool = this.getToolkit(); //得到一个Toolkit对象
		Image myimage = tool.getImage("img/1.png"); //由tool获取图像
		this.setIconImage(myimage);
	}

	/** 
	 * 初始化登录窗体背景 
	 */
	private void setBackgroudImage() {
		((JPanel) this.getContentPane()).setOpaque(false);
		ImageIcon img = new ImageIcon("img/loginbg.jpg"); // 添加图片  
		JLabel lb_backgroud = new JLabel(img);
		this.getLayeredPane().add(lb_backgroud, new Integer(Integer.MIN_VALUE));
		lb_backgroud.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		user = new javax.swing.JLabel();
		pass = new javax.swing.JLabel();
		userName = new javax.swing.JTextField();
		submit = new javax.swing.JLabel();
		reset = new javax.swing.JLabel();
		passWord = new javax.swing.JPasswordField();
		captchatext = new javax.swing.JTextField();
		captcha = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u767b\u5f55");

		user.setIcon(new javax.swing.ImageIcon(
				"img\\user.png")); // NOI18N

		pass.setIcon(new javax.swing.ImageIcon(
				"img\\password.png")); // NOI18N

		userName.setFont(new java.awt.Font("楷体", 0, 20));
		userName.setBorder(null);

		submit.setIcon(new javax.swing.ImageIcon(
				"img\\submit.png")); // NOI18N
		submit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				submitMouseClicked(evt);
			}
		});

		reset.setIcon(new javax.swing.ImageIcon(
				"img\\reset.png")); // NOI18N
		reset.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				resetMouseClicked(evt);
			}
		});

		passWord.setFont(new java.awt.Font("宋体", 0, 20));
		passWord.setBorder(null);

		captchatext.setFont(new java.awt.Font("楷体", 0, 20));
		captchatext.setBorder(null);

		captcha.setText("\u9a8c\u8bc1\u7801");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(371, 371, 371)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(pass)
														.addComponent(user))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								reset)
																						.addGap(
																								121,
																								121,
																								121)
																						.addComponent(
																								submit)
																						.addGap(
																								32,
																								32,
																								32))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								captchatext,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								158,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								validCode)
																						.addGap(
																								21,
																								21,
																								21)))
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				passWord,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				245,
																				Short.MAX_VALUE)
																		.addComponent(
																				userName,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				245,
																				Short.MAX_VALUE)))
										.addGap(395, 395, 395)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(324, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(userName)
														.addComponent(user))
										.addGap(40, 40, 40)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(pass)
														.addComponent(
																passWord,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(validCode)
														.addComponent(
																captchatext,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																32,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(37, 37, 37)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(submit)
														.addComponent(reset))
										.addGap(71, 71, 71)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/** 
	 * 重置登录页面
	 */
	private void resetMouseClicked(java.awt.event.MouseEvent evt) {
		this.userName.setText("");
		this.passWord.setText("");
		this.captchatext.setText("");
	}

	/** 
	 * 提交登录页面
	 */

	@SuppressWarnings("deprecation")
	private void submitMouseClicked(java.awt.event.MouseEvent evt) {
		String username = this.userName.getText();
		String password = this.passWord.getText();
		boolean b = loginDao.validate(username, password);
		if (b) {
			String captchatext = this.captchatext.getText();
			String code = validCode.getCode();
			if (captchatext == null || captchatext.equals("")) {
				JOptionPane.showMessageDialog(null, "验证码不能为空！");
				return;
			}
			if (!captchatext.equalsIgnoreCase(code)) {
				JOptionPane.showMessageDialog(null, "验证码不正确！");
				return;
			}
			//JOptionPane.showMessageDialog(null, "用户名和密码正确，登录成功");//弹出提示框
			new MainView().setVisible(true);
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(null, "用户名和密码不正确，请重新登录");//弹出提示框
			return;
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel captcha;
	private javax.swing.JTextField captchatext;
	private javax.swing.JLabel pass;
	private javax.swing.JPasswordField passWord;
	private javax.swing.JLabel reset;
	private javax.swing.JLabel submit;
	private javax.swing.JLabel user;
	private javax.swing.JTextField userName;
	// End of variables declaration//GEN-END:variables

}