/*
 * MainView.java
 *
 * Created on __DATE__, __TIME__
 */

package page;

import java.awt.Image;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import dao.BookQueryDao;

/**
 *
 * @author  __USER__
 */
public class MainView extends javax.swing.JFrame {
	/**
	 * 序列号
	 */
	private static final long serialVersionUID = 1L;
	
	
	BookQueryDao bqd = new BookQueryDao();

	/** Creates new form MainView */
	public MainView() {
		initComponents();
		//设置窗体大小和位置
		this.setBounds(150, 50, 1050, 650);
		//设置背景
		setBackgroudImage();
		//窗体大小不可变
		this.setResizable(false);
		
		//设置窗体图标
		Toolkit tool = this.getToolkit(); //得到一个Toolkit对象
		Image myimage = tool.getImage("img/2.png"); //由tool获取图像
		this.setIconImage(myimage);
	}

	/** 
	 * 初始化主界面窗体背景 
	 */
	private void setBackgroudImage() {
		((JPanel) this.getContentPane()).setOpaque(false);
		ImageIcon img = new ImageIcon("img/mainviewbg.jpg"); // 添加图片  
		JLabel lb_backgroud = new JLabel(img);
		this.getLayeredPane().add(lb_backgroud, new Integer(Integer.MIN_VALUE));
		lb_backgroud.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lentBack = new javax.swing.JLabel();
		bookManager = new javax.swing.JLabel();
		aboutus = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u56fe\u4e66\u7ba1\u7406\u7cfb\u7edf");

		lentBack.setIcon(new javax.swing.ImageIcon(
				"img\\right.png")); // NOI18N
		lentBack.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lentBackMouseClicked(evt);
			}
		});

		bookManager.setIcon(new javax.swing.ImageIcon(
				"img\\left.png")); // NOI18N
		bookManager.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				bookManagerMouseClicked(evt);
			}
		});

		aboutus.setFont(new java.awt.Font("楷体", 0, 20));
		aboutus.setForeground(new java.awt.Color(255, 255, 255));
		aboutus.setText("\u5173\u4e8e\u6211\u4eec");
		aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				aboutusMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap(311, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				bookManager)
																		.addGap(
																				66,
																				66,
																				66)
																		.addComponent(
																				lentBack)
																		.addGap(
																				116,
																				116,
																				116))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				aboutus)
																		.addGap(
																				42,
																				42,
																				42)))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(35, 35, 35)
										.addComponent(aboutus)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												198, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				lentBack)
																		.addGap(
																				92,
																				92,
																				92))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				bookManager)
																		.addGap(
																				67,
																				67,
																				67)))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	/** 
	 * 跳转到关于我们页面
	 */
	private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {
		new AboutUs().setVisible(true);
		this.dispose();
	}

	/** 
	 * 跳转到图书管理页面
	 */
	private void bookManagerMouseClicked(java.awt.event.MouseEvent evt) {
		new BookManager().setVisible(true);
		this.dispose();
	}

	/** 
	 * 跳转到借还服务页面
	 */
	private void lentBackMouseClicked(java.awt.event.MouseEvent evt) {
		new LentBack().setVisible(true);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel aboutus;
	private javax.swing.JLabel bookManager;
	private javax.swing.JLabel lentBack;
	// End of variables declaration//GEN-END:variables

}